---
title: "Test"
author: "Alberto"
date: "January 23, 2019"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
#library(datasets)
library("ggplot2")
#data(faithful)
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
inputPanel(
  #selectInput("n_breaks", label = "Number of bins:",
  #            choices = c(10, 20, 35, 50), selected = 20),

  sliderInput("alpha", label = "Intercept:",
              min = -2, max = 2, value = 0, step = 0.1),
    
  sliderInput("beta", label = "Slope:",
              min = 0, max = 2, value = 1, step = 0.1)
)
```

Column
-----------------------------------------------------------------------
```{r}
renderPlot({
  #hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
  #     xlab = "Duration (minutes)", main = "Geyser eruption duration")
  #
  #dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  #lines(dens, col = "blue")
  eq = function(x, alpha=input$alpha, beta=input$beta){alpha + beta * x}
  p <- ggplot(data = data.frame(x = 0), mapping = aes(x = x))
  p + stat_function(fun=eq, geom="line") + xlab("x") + ylab("y") + xlim(-5,5) + ylim(-5,5)
})
```
